/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSessionidRouteImport } from './routes/sessions/$sessionid'
import { Route as AuthServerRouteImport } from './routes/_auth/server'
import { Route as AuthClientOnlyRouteImport } from './routes/_auth/client-only'
import { Route as AppWorkflowRouteImport } from './routes/_app/workflow'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomizationRouteImport } from './routes/_app/customization'
import { Route as AppBlocklistRouteImport } from './routes/_app/blocklist'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppBackgroundsearchRouteImport } from './routes/_app/backgroundsearch'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAmlRouteImport } from './routes/_app/aml'
import { Route as AppVerificationsIndexRouteImport } from './routes/_app/verifications/index'
import { Route as AppQuestionnairesIndexRouteImport } from './routes/_app/questionnaires/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppVerificationsIdRouteImport } from './routes/_app/verifications/$id'
import { Route as AppQuestionnairesIdRouteImport } from './routes/_app/questionnaires/$id'
import { Route as AppAnalysisIdRouteImport } from './routes/_app/analysis.$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionidRoute = SessionsSessionidRouteImport.update({
  id: '/sessions/$sessionid',
  path: '/sessions/$sessionid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthServerRoute = AuthServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientOnlyRoute = AuthClientOnlyRouteImport.update({
  id: '/client-only',
  path: '/client-only',
  getParentRoute: () => AuthRoute,
} as any)
const AppWorkflowRoute = AppWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomizationRoute = AppCustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => AppRoute,
} as any)
const AppBlocklistRoute = AppBlocklistRouteImport.update({
  id: '/blocklist',
  path: '/blocklist',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBackgroundsearchRoute = AppBackgroundsearchRouteImport.update({
  id: '/backgroundsearch',
  path: '/backgroundsearch',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAmlRoute = AppAmlRouteImport.update({
  id: '/aml',
  path: '/aml',
  getParentRoute: () => AppRoute,
} as any)
const AppVerificationsIndexRoute = AppVerificationsIndexRouteImport.update({
  id: '/verifications/',
  path: '/verifications/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionnairesIndexRoute = AppQuestionnairesIndexRouteImport.update({
  id: '/questionnaires/',
  path: '/questionnaires/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerificationsIdRoute = AppVerificationsIdRouteImport.update({
  id: '/verifications/$id',
  path: '/verifications/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionnairesIdRoute = AppQuestionnairesIdRouteImport.update({
  id: '/questionnaires/$id',
  path: '/questionnaires/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalysisIdRoute = AppAnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/aml': typeof AppAmlRoute
  '/analytics': typeof AppAnalyticsRoute
  '/backgroundsearch': typeof AppBackgroundsearchRoute
  '/billing': typeof AppBillingRoute
  '/blocklist': typeof AppBlocklistRoute
  '/customization': typeof AppCustomizationRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/settings': typeof AppSettingsRoute
  '/workflow': typeof AppWorkflowRoute
  '/client-only': typeof AuthClientOnlyRoute
  '/server': typeof AuthServerRoute
  '/sessions/$sessionid': typeof SessionsSessionidRoute
  '/analysis/$id': typeof AppAnalysisIdRoute
  '/questionnaires/$id': typeof AppQuestionnairesIdRoute
  '/verifications/$id': typeof AppVerificationsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/questionnaires': typeof AppQuestionnairesIndexRoute
  '/verifications': typeof AppVerificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/aml': typeof AppAmlRoute
  '/analytics': typeof AppAnalyticsRoute
  '/backgroundsearch': typeof AppBackgroundsearchRoute
  '/billing': typeof AppBillingRoute
  '/blocklist': typeof AppBlocklistRoute
  '/customization': typeof AppCustomizationRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/settings': typeof AppSettingsRoute
  '/workflow': typeof AppWorkflowRoute
  '/client-only': typeof AuthClientOnlyRoute
  '/server': typeof AuthServerRoute
  '/sessions/$sessionid': typeof SessionsSessionidRoute
  '/analysis/$id': typeof AppAnalysisIdRoute
  '/questionnaires/$id': typeof AppQuestionnairesIdRoute
  '/verifications/$id': typeof AppVerificationsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/questionnaires': typeof AppQuestionnairesIndexRoute
  '/verifications': typeof AppVerificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/aml': typeof AppAmlRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/backgroundsearch': typeof AppBackgroundsearchRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/blocklist': typeof AppBlocklistRoute
  '/_app/customization': typeof AppCustomizationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workflow': typeof AppWorkflowRoute
  '/_auth/client-only': typeof AuthClientOnlyRoute
  '/_auth/server': typeof AuthServerRoute
  '/sessions/$sessionid': typeof SessionsSessionidRoute
  '/_app/analysis/$id': typeof AppAnalysisIdRoute
  '/_app/questionnaires/$id': typeof AppQuestionnairesIdRoute
  '/_app/verifications/$id': typeof AppVerificationsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/questionnaires/': typeof AppQuestionnairesIndexRoute
  '/_app/verifications/': typeof AppVerificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/aml'
    | '/analytics'
    | '/backgroundsearch'
    | '/billing'
    | '/blocklist'
    | '/customization'
    | '/dashboard'
    | '/documents'
    | '/settings'
    | '/workflow'
    | '/client-only'
    | '/server'
    | '/sessions/$sessionid'
    | '/analysis/$id'
    | '/questionnaires/$id'
    | '/verifications/$id'
    | '/api/auth/$'
    | '/questionnaires'
    | '/verifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/aml'
    | '/analytics'
    | '/backgroundsearch'
    | '/billing'
    | '/blocklist'
    | '/customization'
    | '/dashboard'
    | '/documents'
    | '/settings'
    | '/workflow'
    | '/client-only'
    | '/server'
    | '/sessions/$sessionid'
    | '/analysis/$id'
    | '/questionnaires/$id'
    | '/verifications/$id'
    | '/api/auth/$'
    | '/questionnaires'
    | '/verifications'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/sign-in'
    | '/sign-up'
    | '/_app/aml'
    | '/_app/analytics'
    | '/_app/backgroundsearch'
    | '/_app/billing'
    | '/_app/blocklist'
    | '/_app/customization'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/settings'
    | '/_app/workflow'
    | '/_auth/client-only'
    | '/_auth/server'
    | '/sessions/$sessionid'
    | '/_app/analysis/$id'
    | '/_app/questionnaires/$id'
    | '/_app/verifications/$id'
    | '/api/auth/$'
    | '/_app/questionnaires/'
    | '/_app/verifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SessionsSessionidRoute: typeof SessionsSessionidRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionid': {
      id: '/sessions/$sessionid'
      path: '/sessions/$sessionid'
      fullPath: '/sessions/$sessionid'
      preLoaderRoute: typeof SessionsSessionidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/server': {
      id: '/_auth/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof AuthServerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/client-only': {
      id: '/_auth/client-only'
      path: '/client-only'
      fullPath: '/client-only'
      preLoaderRoute: typeof AuthClientOnlyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/workflow': {
      id: '/_app/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AppWorkflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customization': {
      id: '/_app/customization'
      path: '/customization'
      fullPath: '/customization'
      preLoaderRoute: typeof AppCustomizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blocklist': {
      id: '/_app/blocklist'
      path: '/blocklist'
      fullPath: '/blocklist'
      preLoaderRoute: typeof AppBlocklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backgroundsearch': {
      id: '/_app/backgroundsearch'
      path: '/backgroundsearch'
      fullPath: '/backgroundsearch'
      preLoaderRoute: typeof AppBackgroundsearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aml': {
      id: '/_app/aml'
      path: '/aml'
      fullPath: '/aml'
      preLoaderRoute: typeof AppAmlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verifications/': {
      id: '/_app/verifications/'
      path: '/verifications'
      fullPath: '/verifications'
      preLoaderRoute: typeof AppVerificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/questionnaires/': {
      id: '/_app/questionnaires/'
      path: '/questionnaires'
      fullPath: '/questionnaires'
      preLoaderRoute: typeof AppQuestionnairesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/verifications/$id': {
      id: '/_app/verifications/$id'
      path: '/verifications/$id'
      fullPath: '/verifications/$id'
      preLoaderRoute: typeof AppVerificationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/questionnaires/$id': {
      id: '/_app/questionnaires/$id'
      path: '/questionnaires/$id'
      fullPath: '/questionnaires/$id'
      preLoaderRoute: typeof AppQuestionnairesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analysis/$id': {
      id: '/_app/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AppAnalysisIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAmlRoute: typeof AppAmlRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBackgroundsearchRoute: typeof AppBackgroundsearchRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBlocklistRoute: typeof AppBlocklistRoute
  AppCustomizationRoute: typeof AppCustomizationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkflowRoute: typeof AppWorkflowRoute
  AppAnalysisIdRoute: typeof AppAnalysisIdRoute
  AppQuestionnairesIdRoute: typeof AppQuestionnairesIdRoute
  AppVerificationsIdRoute: typeof AppVerificationsIdRoute
  AppQuestionnairesIndexRoute: typeof AppQuestionnairesIndexRoute
  AppVerificationsIndexRoute: typeof AppVerificationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAmlRoute: AppAmlRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBackgroundsearchRoute: AppBackgroundsearchRoute,
  AppBillingRoute: AppBillingRoute,
  AppBlocklistRoute: AppBlocklistRoute,
  AppCustomizationRoute: AppCustomizationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkflowRoute: AppWorkflowRoute,
  AppAnalysisIdRoute: AppAnalysisIdRoute,
  AppQuestionnairesIdRoute: AppQuestionnairesIdRoute,
  AppVerificationsIdRoute: AppVerificationsIdRoute,
  AppQuestionnairesIndexRoute: AppQuestionnairesIndexRoute,
  AppVerificationsIndexRoute: AppVerificationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthClientOnlyRoute: typeof AuthClientOnlyRoute
  AuthServerRoute: typeof AuthServerRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthClientOnlyRoute: AuthClientOnlyRoute,
  AuthServerRoute: AuthServerRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SessionsSessionidRoute: SessionsSessionidRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
